/*
 * EnoviaRestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.yenaplus.backend.controllers;

import static org.junit.Assert.assertNotNull;

import com.yenaplus.backend.EnoviaRestAPIClient;
import com.yenaplus.backend.exceptions.ApiException;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class CommonControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static EnoviaRestAPIClient client;
    
    /**
     * Controller instance (for all tests).
     */
    private static CommonController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getCommonController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

}
