/*
 * EnoviaRestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.yenaplus.backend.controllers;

import com.yenaplus.backend.ApiHelper;
import com.yenaplus.backend.Server;
import com.yenaplus.backend.exceptions.ApiException;
import com.yenaplus.backend.http.request.HttpMethod;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class TestController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public TestController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * @param  count  Required parameter: Example:
     * @param  pid  Required parameter: Example:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void createDummyStructureWithDocuments(
            final int count,
            final String pid) throws ApiException, IOException {
        prepareCreateDummyStructureWithDocumentsRequest(count, pid).execute();
    }

    /**
     * @param  count  Required parameter: Example:
     * @param  pid  Required parameter: Example:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> createDummyStructureWithDocumentsAsync(
            final int count,
            final String pid) {
        try { 
            return prepareCreateDummyStructureWithDocumentsRequest(count, pid).executeAsync(); 
        } catch (Exception e) {  
            throw new CompletionException(e); 
        }
    }

    /**
     * Builds the ApiCall object for createDummyStructureWithDocuments.
     */
    private ApiCall<Void, ApiException> prepareCreateDummyStructureWithDocumentsRequest(
            final int count,
            final String pid) throws IOException {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.BACKEND.value())
                        .path("/{pid}")
                        .queryParam(param -> param.key("count")
                                .value(count).isRequired(false))
                        .templateParam(param -> param.key("pid").value(pid)
                                .shouldEncode(true))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}